## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := generic-gnu
ALL_TARGETS += libs

PREFIX=/usr/local
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8-nopost-nomt-nodocs-generic-gnu-v1.14.1
else
DIST_DIR?=$(DESTDIR)/usr/local
endif
LIBSUBDIR=lib

VERSION_STRING=v1.14.1

VERSION_MAJOR=1
VERSION_MINOR=14
VERSION_PATCH=1

CONFIGURE_ARGS=--target=generic-gnu --enable-vp8 --disable-vp9 --enable-static --disable-shared --enable-pic --disable-examples --disable-tools --disable-docs --disable-unit-tests --disable-install-docs --disable-install-bins --enable-realtime-only --enable-onthefly-bitpacking --disable-multithread --extra-cflags=-fPIC -O2 --disable-runtime-cpu-detect
CONFIGURE_ARGS?=--target=generic-gnu --enable-vp8 --disable-vp9 --enable-static --disable-shared --enable-pic --disable-examples --disable-tools --disable-docs --disable-unit-tests --disable-install-docs --disable-install-bins --enable-realtime-only --enable-onthefly-bitpacking --disable-multithread --extra-cflags=-fPIC -O2 --disable-runtime-cpu-detect
