## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
SRC_PATH="D:/tdcare/td-zt9/smartward/rust-sdks/libvpx"
SRC_PATH_BARE=D:/tdcare/td-zt9/smartward/rust-sdks/libvpx
BUILD_PFX=
TOOLCHAIN=generic-gnu
ASM_CONVERSION=D:/tdcare/td-zt9/smartward/rust-sdks/libvpx/build/make/ads2gas.pl
GEN_VCPROJ=
MSVS_ARCH_DIR=

CC=/c/Users/tzw/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang --target=armv7a-linux-androideabi21
CXX=/c/Users/tzw/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ --target=armv7a-linux-androideabi21
AR=/c/Users/tzw/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar
LD=/c/Users/tzw/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ --target=armv7a-linux-androideabi21
AS=/c/Users/tzw/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang --target=armv7a-linux-androideabi21
STRIP=/c/Users/tzw/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-strip
NM=/c/Users/tzw/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-nm

CFLAGS  =  -DNDEBUG -O3 -fPIC -Wall -Wdisabled-optimization -Wextra-semi -Wextra-semi-stmt -Wfloat-conversion -Wformat=2 -Wparentheses-equality -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wshadow -Wuninitialized -Wunreachable-code-aggressive -Wunused -Wextra -Wundef -Wframe-larger-than=52000 -std=gnu99 -Wshorten-64-to-32 -fPIC -O2
CXXFLAGS  =  -DNDEBUG -O3 -fPIC -Wall -Wdisabled-optimization -Wextra-semi -Wextra-semi-stmt -Wfloat-conversion -Wformat=2 -Wparentheses-equality -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wshadow -Wuninitialized -Wunreachable-code-aggressive -Wunused -Wextra -Wc++14-extensions -Wc++17-extensions -Wc++20-extensions -Wnon-virtual-dtor -std=gnu++11 -fPIC -O2
ARFLAGS = -crs$(if $(quiet),,v)
LDFLAGS = 
ASFLAGS = 
extralibs = 
AS_SFX    = .S
EXE_SFX   = 
VCPROJ_SFX = 
RTCD_OPTIONS = 
LIBWEBM_CXXFLAGS =  -Wno-shadow
LIBYUV_CXXFLAGS =  -Wno-missing-declarations -Wno-missing-prototypes -Wno-pass-failed -Wno-shadow -Wno-unused-parameter
fmt_deps = sed -e 's;^\([a-zA-Z0-9_]*\)\.o;${@:.d=.o} $@;'
HAVE_VPX_PORTS=yes
HAVE_UNISTD_H=yes
CONFIG_DEPENDENCY_TRACKING=yes
CONFIG_INSTALL_LIBS=yes
CONFIG_GCC=yes
CONFIG_PIC=yes
CONFIG_VP8_ENCODER=yes
CONFIG_VP8_DECODER=yes
CONFIG_VP8=yes
CONFIG_ENCODERS=yes
CONFIG_DECODERS=yes
CONFIG_SPATIAL_RESAMPLING=yes
CONFIG_REALTIME_ONLY=yes
CONFIG_ONTHEFLY_BITPACKING=yes
CONFIG_STATIC=yes
CONFIG_OS_SUPPORT=yes
CONFIG_WEBM_IO=yes
CONFIG_LIBYUV=yes
CONFIG_TEMPORAL_DENOISING=yes
HAVE_GNU_STRIP=yes
